"use client";

import { useLanguage } from "@/components/app-shell";

export function PageHeader({id,title,description,action}:{id:string;title:string;description:string;action?:string}){
  return <div className="page-header"><div><p className="eyebrow">{id} · {useLanguage().t("synthetic")}</p><h1>{title}</h1><p>{description}</p></div>{action?<button className="primary-button">＋ {action}</button>:null}</div>;
}
export function KpiGrid(){const {t}=useLanguage();const metrics=[["1,248",t("overview")],["86",t("pending")],["312",t("completed")],["14",t("priority")]];return <div className="kpi-grid">{metrics.map(([value,label],index)=><article className="kpi" key={label}><div className={`kpi-icon tone-${index}`}>{["⌂","◴","✓","!"][index]}</div><div><strong>{value}</strong><span>{label}</span></div><small>{index===3?"Requiere atención":"↑ 8% este mes"}</small></article>)}</div>}
export function StatusBadge({status="En revisión"}:{status?:string}){return <span className="status-badge">{status}</span>}
export function FilterBar(){const {t}=useLanguage();return <div className="filter-bar"><label><span>⌕</span><input placeholder={t("search")}/></label><button>☷ {t("filters")}</button><button>⇩ {t("export")}</button></div>}
const people=[{name:"María Elena Santos",area:"Los Mina, Santo Domingo Este",type:"Familia",status:"En seguimiento"},{name:"José Miguel Peña",area:"Sabana Perdida, Santo Domingo Norte",type:"Persona",status:"Activo"},{name:"Familia Rosario",area:"Haina, San Cristóbal",type:"Hogar",status:"Evaluación pendiente"},{name:"Lucía Fernández",area:"Villa Mella, Santo Domingo Norte",type:"Persona",status:"Aprobado"}];
export function DataTable(){const {t}=useLanguage();return <div className="table-card"><table><thead><tr><th>Nombre / Registro</th><th>Ubicación</th><th>Tipo</th><th>{t("status")}</th><th></th></tr></thead><tbody>{people.map((row)=><tr key={row.name}><td><span className="avatar">{row.name.split(" ").map((p)=>p[0]).slice(0,2)}</span><strong>{row.name}</strong></td><td>{row.area}</td><td>{row.type}</td><td><StatusBadge status={row.status}/></td><td><button aria-label={`${t("view")} ${row.name}`}>→</button></td></tr>)}</tbody></table></div>}
export function StateGallery(){const {t}=useLanguage();return <details className="state-gallery"><summary>Estados de interfaz</summary><div><span>◌ {t("loading")}</span><span>○ {t("empty")}</span><span>⚠ {t("error")}</span><span>🔒 {t("unauthorized")}</span></div></details>}
export function ActivityPanel(){return <section className="panel"><div className="panel-title"><h2>Actividad reciente</h2><button>Ver todo</button></div>{["Evaluación alimentaria actualizada","Solicitud enviada a aprobación","Entrega completada con evidencia"].map((item,index)=><div className="activity" key={item}><span>{["✓","→","⌂"][index]}</span><div><strong>{item}</strong><p>Registro sintético · hace {index+1} h</p></div></div>)}</section>}
export function FormShell({kind}:{kind:string}){const {t}=useLanguage();return <section className="form-card"><div className="form-grid"><label>Persona u hogar<input defaultValue="Familia Santos (DEMO-0248)"/></label><label>Programa<select defaultValue="food"><option value="food">Apoyo alimentario</option><option value="school">Apoyo educativo</option></select></label><label>Municipio<input defaultValue="Santo Domingo Este"/></label><label>{t("priority")}<select defaultValue="high"><option value="high">Alta</option><option value="normal">Normal</option></select></label><label className="span-2">Descripción<textarea defaultValue={`Registro sintético para la pantalla ${kind}. Requiere revisión humana antes de cualquier decisión.`}/></label></div><div className="form-actions"><button>Guardar borrador</button><button className="primary-button">Enviar para revisión</button></div></section>}
export function Planner(){return <div className="planner"><div className="route-list"><h2>Rutas planificadas</h2>{["Ruta Norte · 8 paradas","Ruta Este · 12 paradas","Ruta Haina · 6 paradas"].map((r,i)=><article key={r}><span>{i+1}</span><div><strong>{r}</strong><p>Vehículo DEMO-{14+i} · 08:30</p></div></article>)}</div><div className="map-shell"><span>Mapa de demostración</span><i className="pin pin-a">1</i><i className="pin pin-b">2</i><i className="pin pin-c">3</i></div></div>}
