"use client";

import Link from "next/link";
import { useLanguage } from "@/components/app-shell";

const format = (template: string, values: Record<string, string | number>) =>
  Object.entries(values).reduce((result, [key, value]) => result.replace(`{${key}}`, String(value)), template);

export function PageHeader({id,title,description,action,actionHref}:{id:string;title:string;description:string;action?:string;actionHref?:string}){
  const {t}=useLanguage();
  return <div className="page-header"><div><p className="eyebrow">{id} · {t("synthetic")}</p><h1>{title}</h1><p>{description}</p></div>{action&&actionHref?<Link className="primary-button" href={actionHref}>＋ {action}</Link>:null}</div>;
}
export function KpiGrid(){const {t}=useLanguage();const metrics=[["1,248",t("overview")],["86",t("pending")],["312",t("completed")],["14",t("priority")]];return <div className="kpi-grid">{metrics.map(([value,label],index)=><article className="kpi" key={label}><div className={`kpi-icon tone-${index}`}>{["⌂","◴","✓","!"][index]}</div><div><strong>{value}</strong><span>{label}</span></div><small>{index===3?t("attentionRequired"):t("monthChange")}</small></article>)}</div>}
export function StatusBadge({status}:{status:string}){return <span className="status-badge">{status}</span>}
export function FilterBar(){const {t}=useLanguage();return <div className="filter-bar"><label><span>⌕</span><input aria-label={t("search")} placeholder={t("search")}/></label><button>☷ {t("filters")}</button><button>⇩ {t("export")}</button></div>}
const people=[
  {name:"María Elena Santos",areaEs:"Los Mina, Santo Domingo Este",areaEn:"Los Mina, Santo Domingo East",type:"family",status:"followUp"},
  {name:"José Miguel Peña",areaEs:"Sabana Perdida, Santo Domingo Norte",areaEn:"Sabana Perdida, Santo Domingo North",type:"person",status:"active"},
  {name:"Familia Rosario",areaEs:"Haina, San Cristóbal",areaEn:"Haina, San Cristóbal",type:"household",status:"assessmentPending"},
  {name:"Lucía Fernández",areaEs:"Villa Mella, Santo Domingo Norte",areaEn:"Villa Mella, Santo Domingo North",type:"person",status:"approved"},
] as const;
export function DataTable({detailHref="/screens/idn-022"}:{detailHref?:string}){const {locale,t}=useLanguage();return <div className="table-card"><table><thead><tr><th>{t("nameRecord")}</th><th>{t("area")}</th><th>{t("type")}</th><th>{t("status")}</th><th></th></tr></thead><tbody>{people.map((row)=><tr key={row.name}><td><span className="avatar">{row.name.split(" ").map((part)=>part[0]).slice(0,2)}</span><strong>{row.name}</strong></td><td>{locale==="es"?row.areaEs:row.areaEn}</td><td>{t(row.type)}</td><td><StatusBadge status={t(row.status)}/></td><td><Link className="record-link" href={detailHref} aria-label={`${t("view")} ${row.name}`}>→</Link></td></tr>)}</tbody></table></div>}
export function StateGallery(){const {t}=useLanguage();return <details className="state-gallery"><summary>{t("interfaceStates")}</summary><div><span>◌ {t("loading")}</span><span>○ {t("empty")}</span><span>⚠ {t("error")}</span><span>🔒 {t("unauthorized")}</span></div></details>}
export function ActivityPanel(){const {t}=useLanguage();const items=["updatedAssessment","sentApproval","deliveryCompleted"] as const;return <section className="panel"><div className="panel-title"><h2>{t("recentActivity")}</h2><button>{t("viewAll")}</button></div>{items.map((item,index)=><div className="activity" key={item}><span>{["✓","→","⌂"][index]}</span><div><strong>{t(item)}</strong><p>{t("syntheticRecord")} · {format(t("hoursAgo"),{hours:index+1})}</p></div></div>)}</section>}
export function FormShell({kind}:{kind:string}){const {t}=useLanguage();
  if(kind==="IDN-021")return <section className="form-card"><div className="form-grid"><label>{t("givenNames")}<input defaultValue="Daniela"/></label><label>{t("familyNames")}<input defaultValue="Méndez"/></label><label>{t("birthDate")}<input type="date" defaultValue="1992-05-14"/></label><label>{t("phone")}<input type="tel" defaultValue="+1 809 555 0142"/></label><label className="span-2">{t("address")}<input defaultValue="Calle Sintética 14, Santo Domingo Este"/></label></div><div className="duplicate-panel"><strong>{t("duplicateSearch")}</strong><p>{t("duplicateSearchBody")}</p><button type="button">{t("runDuplicateSearch")}</button></div><div className="form-actions"><button>{t("saveDraft")}</button><button className="primary-button" disabled>{t("submitReview")}</button></div></section>;
  if(kind==="FAM-031")return <section className="form-card"><div className="form-grid"><label>{t("householdName")}<input defaultValue="Familia Méndez"/></label><label>{t("primaryContact")}<input defaultValue="Daniela Méndez"/></label><label>{t("householdMembers")}<input type="number" min="1" defaultValue="4"/></label><label>{t("municipality")}<input defaultValue="Santo Domingo Este"/></label><label className="span-2">{t("address")}<input defaultValue="Calle Sintética 14, Santo Domingo Este"/></label></div><div className="form-actions"><button>{t("saveDraft")}</button><button className="primary-button">{t("submitReview")}</button></div></section>;
  return <section className="form-card"><div className="form-grid"><label>{t("personHousehold")}<input defaultValue="Familia Santos (DEMO-0248)"/></label><label>{t("programme")}<select defaultValue="food"><option value="food">{t("foodSupport")}</option><option value="school">{t("educationSupport")}</option></select></label><label>{t("municipality")}<input defaultValue="Santo Domingo Este"/></label><label>{t("priority")}<select defaultValue="high"><option value="high">{t("high")}</option><option value="normal">{t("normal")}</option></select></label><label className="span-2">{t("description")}<textarea defaultValue={format(t("demoForm"),{screen:kind})}/></label></div><div className="form-actions"><button>{t("saveDraft")}</button><button className="primary-button">{t("submitReview")}</button></div></section>}
export function Planner(){const {t}=useLanguage();const routes=["northRoute","eastRoute","hainaRoute"] as const;return <div className="planner"><div className="route-list"><h2>{t("plannedRoutes")}</h2>{routes.map((route,index)=><article key={route}><span>{index+1}</span><div><strong>{t(route)}</strong><p>{t("vehicle")} DEMO-{14+index} · 08:30</p></div></article>)}</div><div className="map-shell"><span>{t("demoMap")}</span><i className="pin pin-a">1</i><i className="pin pin-b">2</i><i className="pin pin-c">3</i></div></div>}
